server.port: 8081

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJQTUFHPLLNDIBCWQ
  secretKey: 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
  bucketName: student-artifacts-bangalore-13