spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJQTUFHPLLNDIBCWQ
  secretKey: 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
  bucketName: student-artifacts-bangalore-13

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
